config/routes.rb
Rails.application.routes.draw do
    root to:"toppages#index"
   
    
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    
   
    get "signup", to: "users#new"
     
    resources :users, only: [:index, :show, :new, :create, :destroy] do
        member do
            get :likes
        end
    end
   
    resources :bookposts, only: [:index, :show, :new, :create, :destroy]
    resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookpost.rb
class Bookpost < ApplicationRecord
  belongs_to :user
  
   validates :content, presence: true, length: { maximum: 200 }
    validates :title, presence: true, length: { maximum: 30 }
    
    has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bookpost
  
 
end

app/models/user.rb
class User < ApplicationRecord
     before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 20 }
     validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :bookposts
    has_many :likes
    has_many :likings, through: :likes, source: :bookpost
    
    
    def like(other_bookpost)
        unless self == other_bookpost
        self.likes.find_or_create_by(bookpost_id: other_bookpost.id)
        end
    end
    
    def unlike(other_bookpost)
        like = self.likes.find_by(bookpost_id: other_bookpost.id)
        like.destroy if like
    end
    
    def liking?(other_bookpost)
        self.likings.include?(other_bookpost)
    end
    
    def feed_bookposts
     Bookpost.where(user_id: self.liking_ids + [self.id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
    include SessionsHelper
    include Pagy::Backend
    
    private
    
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        else
            @user = current_user
        end
    end
        
end

app/controllers/bookposts_controller.rb
class BookpostsController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :correct_user, only: [:destroy]
    
  def index
    @pagy, @bookposts = pagy(Bookpost.order(id: :desc), items: 25)
    
  end
  
  def show
    @bookpost = Bookpost.find(params[:id])
  end
  
  def new
    @bookpost = Bookpost.new
    @user = current_user
  end

  def create
    @user = current_user
    @bookpost = current_user.bookposts.build(bookpost_params)
    if @bookpost.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else 
      @pagy, @bookposts = pagy(current_user.bookposts.order(id: :desc))
      flash.now[:danger] = '投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @bookpost.destroy
    flash[:danger] = "投稿を削除しました。"
    redirect_to @bookpost
  end

  

  private

  def bookpost_params
    params.require(:bookpost).permit(:content, :title)
  end
  
  def correct_user
    @bookpost = current_user.bookposts.find_by(id: params[:id])
    unless @bookpost
      redirect_to root_url
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in, only: [:create, :destroy]
  
  
    
  def create
    bookpost = Bookpost.find(params[:like_id])
    current_user.like(bookpost)
    flash[:success] = "投稿をいいねしました。"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    bookpost = Bookpost.find(params[:like_id])
    current_user.unlike(bookpost)
    flash[:danger] = "いいねを解除しました"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
 def new 
   @user = current_user
 end  
 
 def create
     email = params[:session][:email].downcase
     password = params[:session][:password]
     if login(email, password)
         flash[:success] = "ログインに成功しました。"
         redirect_to bookposts_path(@bookpost)
     else
         flash.now[:danger] = "ログインに失敗しました。"
         render :new
     end
 end
 
 def destroy
     session[:user_id] = nil
     flash[:success] = "ログアウトしました。"
     redirect_to root_url
 end
 
 private
 
 def login(email, password)
     @user = User.find_by(email: email)
     if @user && @user.authenticate(password)
         session[:user_id] = @user.id
         return true
     else
         return false
     end
 end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    if logged_in?
      @user = current_user
      @bookpost = current_user.bookposts.build
      @pagy, @bookposts = pagy(current_user.bookposts.order(id: :desc))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :likes]
  
  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 25)
    @user = current_user
  
  end

  def show
    @user = User.find(params[:id])
    @pagy, @bookposts = pagy(@user.bookposts.order(id: :desc)) 
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザーを登録しました。"
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @pagy, @likings = pagy(@user.likings)
  end
  
  private
  
  def bookpost_params
    params.require(:bookpost).permit(:content, :title)
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/bookposts/_bookposts.html.erb
<% if bookposts.any? %>
     <% bookposts.each do |bookpost| %>
      
      
            <div class="m-2 text-primary "><h3>本のタイトル</h3>
               <p><%= bookpost.title %></p>
            </div>
          
          <div class= "m-2 text-primary"><h4>本のレビュー</h4>
             <p><%=  bookpost.content %></p>
          </div>
         <div>
            <% if current_user == bookpost.user %>
            <%= link_to "削除", bookpost, method: :delete, data: { confirm: "削除してもいいですか？" }, class: "btn btn-danger m-2  w-40" %>
          </div>
         <div>
            <% else bookpost.user == current_user %>
            <%= render 'likes/like_button', bookpost: bookpost %>
            <% end %>
         </div>
           <% end %>
         <div class="offset-sm-2">
           <%== pagy_bootstrap_nav(@pagy) %>
         </div>
      
<% end %>

app/views/bookposts/index.html.erb
<div class="text-center">
       <h1>投稿一覧</h1>
    </div>
 
 <%= render 'bookposts/bookposts', bookposts: @bookposts %>
    

app/views/bookposts/new.html.erb
<div class="text-center">
   <h1>投稿ページ</h1>
     
   <div class="row">
     <div class="col-sm-6 offset-sm-3" >
       
          <%= form_with(model: @bookpost) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
         
          <div class="mb-3">
            <%= f.label :title, 'おすすめ本のタイトル' %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="mb-3">
            <%= f.label :content, 'レビュー' %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
            <%= f.submit "投稿", class: "btn btn-primary" %>
            <% end %>
        
          <div class="text-bottom">
              <div class=  "text-black"><p>タイトルは30文字,レビューは200文字以内に収めてください</p>
                         
              </div>
          </div>
      </div>
    </div>
  </div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
        <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
            <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
     <nav class="navbar navbar-expand-sm navbar-#dbffed bg-#dbffed">
          <div class="container-fluid ps-5 pe-5">
      
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                 <span class="navbar-toggler-icon"></span>
              </button>

             <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                 <% if logged_in? %>
                <div class="btn-group">
                 <ul class="navbar-nav">
                  <li class="ms-3"><%= link_to '投稿一覧', bookposts_path,  class: 'nav-link' %></li>
                   <li class="ms-3"><%= link_to '投稿ページ', new_bookpost_path,  class: 'nav-link' %></li>
                   <li class="ms-3"><%= link_to 'いいね一覧ページ', likes_user_path(@user), class: 'nav-link' %></li>
                    <li class="ms-3"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
         
                  </ul>
        
                </div>
                 <% else %>
                  <ul class="navbar-nav">
                   <li class="nav-item"><%= link_to 'ホーム', root_path, class: 'nav-link' %></li>
                   <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
                   <li class="nav-item"><%= link_to 'ログイン', bookposts_path, class: 'nav-link' %></li>
                   </ul>
                  <% end %>
             </div>
         </div>
     </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Bookposts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

   <body style="background: #dbffed;" data-turbolinks="false">
      <%= render 'layouts/navbar' %>
     
      <div class="container">
         <%= render 'layouts/flash_messages' %>
                              
          <%= yield %>
      </div>
  </body>
    

app/views/likes/_like_button.html.erb
<% if current_user.liking?(bookpost) %>
<%= form_with(model: current_user.likes.find_by(bookpost_id: bookpost.id),  method: :delete) do |f| %>
   <%= hidden_field_tag :like_id, bookpost.id %>
   <%= f.submit "いいね解除ボタン", class: "btn btn-danger m-2 btn-sm" %>
 <% end %>
 <% else %>
   <%= form_with(model: current_user.likes.build) do |f| %>
    <%= hidden_field_tag :like_id, bookpost.id,id: "like_#{bookpost.id}" %>
    <%= f.submit "いいねボタン", class: "btn btn-primary m-2 btn-sm" %>
  <% end %>
<% end %>

 

app/views/toppages/index.html.erb
 <% if logged_in? %>
   <div class="row">
     <aside class="col-sm-4">
       <%= form_with(model: @bookpost) do |f| %>
        <% end %>
     </aside>
       <div class="col-sm-8 ">
         <%= render 'bookposts/bookposts', bookposts: @bookposts %>
       </div>
   </div>
   
    <% else %>
<div class="bg-primary p-3 p-sm-5 my-4 rounded">
  <div class="text-center text-white">
    <h1>おすすめ本紹介サイト</h1>
    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
  <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
</svg>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<%= render "users", users: @users %>

app/views/users/likes.html.erb
<div class="text-center">
  <h1>いいね一覧ページ</h1>
</div>
 
   <%= render "bookposts/bookposts", bookposts: @likings %>
    

app/views/users/new.html.erb
<div class="text-center">
    <h1>会員登録</h1>
</div>
   
     <div class="col-sm-6 offset-sm-3">
         
       <%= form_with(model: @user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
  
        <div class="mb-3">
          <%= f.label :name, '氏名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
 
        <div class="mb-3">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= f.label :password_confirmation, '確認' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit '会員登録', class: 'btn btn-primary w-100' %>
        <% end %>
     </div>
  